# Generated by Django 4.2.2 on 2024-01-28 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('turkmen', models.CharField(max_length=150)),
                ('english', models.CharField(max_length=150)),
                ('russian', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('m3u8', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbnails/%d')),
                ('view', models.IntegerField(blank=True, default=0)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('expansion', models.CharField(blank=True, max_length=50, null=True)),
                ('expansion_m', models.CharField(blank=True, default='16:9', max_length=10, null=True)),
                ('server', models.IntegerField(blank=True, default=1)),
                ('category', models.ManyToManyField(blank=True, related_name='videos', to='files.category')),
            ],
        ),
    ]
