# Generated by Django 4.2.2 on 2024-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_tm', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('thumbnail_en', models.ImageField(upload_to='thumbnails/%d')),
                ('thumbnail_tm', models.ImageField(blank=True, null=True, upload_to='thumbnails/%d')),
                ('thumbnail_ru', models.ImageField(blank=True, null=True, upload_to='thumbnails/%d')),
                ('link', models.URLField()),
                ('m3u8_en', models.CharField(blank=True, max_length=500, null=True)),
                ('m3u8_tm', models.CharField(blank=True, max_length=500, null=True)),
                ('m3u8_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('view', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('video_en', models.FileField(blank=True, null=True, upload_to='ads/')),
                ('video_tm', models.FileField(blank=True, null=True, upload_to='ads/')),
                ('video_ru', models.FileField(blank=True, null=True, upload_to='ads/')),
                ('category', models.CharField(choices=[('video', 'video'), ('home', 'home')], default='video', max_length=30)),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.FileField(upload_to='icons')),
                ('information', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('turkmen', models.CharField(max_length=150)),
                ('english', models.CharField(max_length=150)),
                ('russian', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('turkmen', models.CharField(max_length=150)),
                ('english', models.CharField(max_length=150)),
                ('russian', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%d')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner/%d')),
                ('all_video', models.BooleanField(blank=True, default=False)),
                ('view', models.IntegerField(default=0)),
                ('server', models.IntegerField(blank=True, default=1)),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('premium', models.BooleanField(blank=True, default=False)),
                ('geo_protected', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChannelToDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
                ('all_video', models.BooleanField(blank=True, default=False)),
                ('server', models.IntegerField(blank=True, default=0)),
                ('is_processing', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('icon', models.FileField(upload_to='icons')),
                ('turkmen', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
                ('russian', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=400)),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbnails/%d')),
                ('view', models.IntegerField(blank=True, default=0)),
                ('server', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('m3u8', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbnails/%d')),
                ('subtitle', models.FileField(blank=True, null=True, upload_to='subtitles/%d')),
                ('view', models.IntegerField(blank=True, default=0)),
                ('video', models.FileField(upload_to='video/')),
                ('type', models.CharField(choices=[('video', 'Video'), ('shorts', 'Shorts')], default='video', max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('expansion', models.CharField(blank=True, max_length=50, null=True)),
                ('expansion_m', models.CharField(blank=True, default='16:9', max_length=10, null=True)),
                ('premium', models.BooleanField(blank=True, default=False)),
                ('is_processing', models.BooleanField(default=False)),
                ('server', models.IntegerField(blank=True, default=1)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
