# Generated by Django 4.2.2 on 2024-01-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AlterField(
            model_name='video',
            name='server',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
