# Generated by Django 4.2.2 on 2024-01-28 11:33

from django.db import migrations, models
import files.models.video


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_video_video_alter_video_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=files.models.video.id_generator, max_length=30),
        ),
    ]
